Fix namespace build on android
Deals with:

* src/plugins/android/qandroidwebview_p.h:26:1: error: no template named 'JObject';
did you mean 'TestQTNamespace::QtJniTypes::JObject'?

* src/plugins/android/qandroidwebview.cpp:313:1: error: reference to 'QtJniMethods' is ambiguous

Change-Id: I6c90b4c93ffac240708b3bdc6e4b22a3a3b41cfa
Reviewed-by: Christian Strømme <christian.stromme@qt.io>
(cherry picked from commit 35630578ba823691268f8e6ffacc4b6c64eded59)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>